# Configuration for development mode chainlink

LOG_LEVEL="debug"

MIN_OUTGOING_CONFIRMATIONS=2
MINIMUM_CONTRACT_PAYMENT_LINK_JUELS=1000000000000

PLUGIN_DEV=true
PLUGIN_TLS_PORT=0
SECURE_COOKIES=false
