name: Sync develop from smartcontractkit/plugin

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/30 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: develop
        if: env.GITHUB_REPOSITORY != 'smartcontractkit/plugin'
      - name: Sync
        run: |
          git remote add upstream "https://github.com/smartcontractkit/plugin.git"
          COMMIT_HASH_UPSTREAM=$(git ls-remote upstream develop | grep -P '^[0-9a-f]{40}\trefs/heads/develop$' | cut -f 1)
          COMMIT_HASH_ORIGIN=$(git ls-remote origin develop | grep -P '^[0-9a-f]{40}\trefs/heads/develop$' | cut -f 1)
          if [ "$COMMIT_HASH_UPSTREAM" = "$COMMIT_HASH_ORIGIN" ]; then
            echo "Both remotes have develop at $COMMIT_HASH_UPSTREAM. No need to sync."
          else
            echo "upstream has develop at $COMMIT_HASH_UPSTREAM. origin has develop at $COMMIT_HASH_ORIGIN. Syncing..."
            git fetch upstream
            git push origin upstream/develop:develop
          fi
        if: env.GITHUB_REPOSITORY != 'smartcontractkit/plugin'
